<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0" />
<title>{module_pagename}</title>
<link rel="shortcut icon" href="/favicon.png" />
<link rel="apple-touch-icon" href="/home_badge_64.png" />
<link rel="apple-touch-icon-precomposed" href="/home_badge_64.png" />

<link rel="stylesheet" href="/_assets/css/foundation.min.css" />
<link rel="stylesheet" href="/_assets/css/font-awesome.min.css" />
<link rel="stylesheet" href="/_assets/css/fonts.css" />

<link href='https://fonts.googleapis.com/css?family=Montserrat+Subrayada:400,700' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>

<link rel="stylesheet" href="/_assets/css/styles.css" />
<link rel="stylesheet" href="/_assets/css/site-header.css" />
<script src="/_assets/js/vendor/jquery.min.js"></script>
<script src="/_assets/js/parallax.min.js"></script>
<script src="/_assets/js/jquery.easing.1.3.js"></script>

<meta name="google-site-verification" content="GNiCEC3khoN_gz7OFd_rZoKQ9MvsyUJptxQzj43tT1E" />
<meta name="msvalidate.01" content="30990E7D103F1B5D5E0265245B8BECE0" />


<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.2/html5shiv.js"></script>
<script src="//s3.amazonaws.com/nwapi/nwmatcher/nwmatcher-1.2.5-min.js"></script>
<script src="//html5base.googlecode.com/svn-history/r38/trunk/js/selectivizr-1.0.3b.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.1.0/respond.min.js"></script>
<![endif]-->