{% comment -%} the following are from foundation 6 {% endcomment -%}
<script src="/_assets/js/vendor/what-input.min.js"></script>
<script src="/_assets/js/foundation.min.js"></script>
<script>
    $(document).foundation();
</script>
<script src="/_assets/js/plugins.js"></script>
<script src="/_assets/js/scripts.js"></script> 
<script src="/_assets/js/custom.js"></script>
<script src="/_assets/js/skrollr.js"></script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-107291134-1', 'auto', {'allowLinker': true});
    ga('require', 'linker');
    ga('linker:autoLink', ['worldsecuresystems.com','motorcycleyogi.com'],false,true);
    ga('send', 'pageview');
</script>